### ISSUE TITLE
unreadable code syntax coloring

### ISSUE THREAD

**Issue by brandondrew** [thoughtbot/administrate-docs#6]
On [this page](https://administrate-docs.herokuapp.com/adding_custom_field_types) do a search for `#{hash}`, and you'll see that its color is very similar to the background of the code, making it virtually invisible until selected.

**Comment by brandondrew** [comment]
Also, I reached [this form](https://github.com/thoughtbot/administrate/issues/new) through the "Feedback" link on the above-mentioned documentation page.  If you want feedback regarding documentation submitted here instead (as I assume you do), then it may make sense to change that link to point to this repo.

**Comment by tysongach** [comment]
Administrate's documentation has moved to the [main Administrate repo](https://github.com/thoughtbot/administrate).
